### ISSUE TITLE
Watches crash during development

### ISSUE THREAD

**Issue by craigshoemaker** [szwacz/nw-boilerplate#15]
Jakub:

I am really enjoying working with the boilerplate :)

The problem I am having though is that the watches seem to crash during development. After running 

``` shell
npm start
```

...and making a change to a JavaScript file, the script stalls. Here's a screenshot of what I see:

![image](https://cloud.githubusercontent.com/assets/127797/7692056/ca61abac-fd74-11e4-9148-4461bbc113f3.png)

Is there something I am doing wrong?

**Comment by szwacz** [comment]
Nice to hear you like this project :)

Hmm, watch definatelly works for me. Did you try to change and save different files or only one?

**Comment by craigshoemaker** [comment]
I do! It's a wonderful place to start for nw.js apps :smile: 

I've tried making changes to multiple files as well as just a single file. For some reason it just seems to stop processing after the `transpile-watch` task reports as completed.

I am running Gulp version 3.8.11

**Comment by szwacz** [comment]
Same gulp verion here. Do you use gulp watch in other projects on your machine? Is watch in those working without any problems?

**Comment by craigshoemaker** [comment]
Watch works great with other projects. 

I tried re-cloning the project and even tried using other editors (just in case Brackets had watches colliding with the boilerplate), but none of that worked. I also verified I am working off the latest version of node/npm.

I tried a to see if [anything like this showed up in other contexts](https://www.google.com/search?q=gulp%20watch%20not%20working), but didn't see anything that seemed to fit.

Can you think of anything else I might be missing?

**Comment by szwacz** [comment]
Ok, one more, if you run gulp watch by itself (without npm start, just the watch in command line) how it behaves?
I'm asking because `start` task actually starts more processes https://github.com/szwacz/nw-boilerplate/blob/master/tasks/start.js and that might be the problem

**Comment by craigshoemaker** [comment]
Watch by itself (as you describe above) seems to behave just fine.

Interestingly it only seems to be an issue for non-JavaScript files* in the `run` task. The reason I say this is that one of my first tests was to make a small change to the `app.html`. After refreshing the app I noticed that the watch didn't pickup the change on the HTML file. So then I made a change to one of the script files and tried to refresh the application to see the change in the HTML file. This still did not produce a change. 

However, when I try to only change something in the JavaScript files, then everything works as expected (meaning I can immediately refresh the app and see the change in the scripts). Which is odd because the command windows doesn't show that the `copy` or `build` task have run.

\* I tested with HTML and LESS files

**Comment by szwacz** [comment]
Indeed. Now I can reproduce it..... and this is weird as hell.

The problem disappeared for me when I changed glob pattern from `*.html` to `app/**/*.html`, can you chceck if it works for you as well?

**Comment by craigshoemaker** [comment]
That did it!!

Just to verify that we're making the change in the same spot, I updated  the `paths.toCopy` array in `./tasks/build.js` to:

``` javascript
toCopy: [
    'app/node_modules/**',
    'app/bower_components/**',
    'app/vendor/**',
    'app/**/*.html'
],
```

That's the same change you made, right?

**Comment by szwacz** [comment]
Yep! Pushed it to repo.
