### ISSUE TITLE
Unable to compile windows installer

### ISSUE THREAD

**Issue by LukevdPalen** [szwacz/nw-boilerplate#17]
When building the windows installer i bump into an error.
The installer nsis script isn't able to find the required (node_modules)
```
File: failed opening file "c:\Users\IEUser\Desktop\###\tmp\Combiner\node_modules\node-xlsx\no
de_modules\lodash.map\node_modules\lodash.createcallback\node_modules\lodash.keys\node_modules\lodash._shimkeys\node_modules\lodash._ob
jecttypes\LICENSE.txt"
Error in script "c:\Users\IEUser\Desktop\##\tmp\installer.nsi" on line 98 -- aborting creati
on process
```
I tried to compile the windows installer on mac (using `brew install nsis` ) and windows, but both failed. Compiling the Mac dmg works just fine.

Anybody have a clue what the problem might be?

**Comment by szwacz** [comment]
Hmm, when you delete this license file will it throw the same error on different file on this package?

**Comment by LukevdPalen** [comment]
After deleting all `LICENSE.txt` file it wil just throw an error on the next file.

**Comment by LukevdPalen** [comment]
I suggest it has something to do with long file paths. I'm looking in to this..

**Comment by LukevdPalen** [comment]
Resolved the issue by using [https://github.com/zetlen/fenestrate](Fenestrate).
