### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by suprsidr** [szwacz/nw-boilerplate#18]
While running the release script I ran into:
Error in script "C:\Users\<username>\desktop\myapp\tmp\installer.nsi" on line 98 -- aborting creation process
Line in question:
File /r "${src}\*"

Basically it was the windows filename too long error due to 3rd party node modules included in the project.
When I moved my project to c:\myapp all went fine.

Great job.

**Comment by szwacz** [comment]
Yes. Pesky path character limit. Gentelman in #17 issue said that https://github.com/zetlen/fenestrate solves nicely this problem for him.
