### ISSUE TITLE
How to run the app with env = production

### ISSUE THREAD

**Issue by athakral** [szwacz/nw-boilerplate#20]
I tried 

npm start -env production

npm start --env production

npm start --env=production

NODE_ENV=production npm start

the only way I could is by hard coding it in utils.js. tried logging the argv array inside getEnvName in utlis.js but in-vain

Can someone please help

**Comment by szwacz** [comment]
Try:

```
npm start -- --env=production
```

The parameters before `--` are passed to npm itself, after that sign are passed to the script.

**Comment by athakral** [comment]
thanks that worked :)
